---
- id: commit-message-validator
  name: Commit Message Validator
  description: Checks that commit messages are compliant with Lumapps rules.
  entry: hooks/commit-message-validator message
  language: script
  stages: [commit-msg]
