---
- id: commit-message-validator
  name: Commit Message Validator
  description: Checks that commit messages are compliant with Lumapps rules.
  entry: hook-commit-msg.sh
  language: script

- id: pre-push-commit-message-validator
  name: Commit Message Validator
  description: Checks that commit messages are compliant with Lumapps rules.
  entry: hook-pre-push.sh
  language: script
