---
name: 'Commit message validator'
description: >
  Enforce angular commit message convention with minimal dependency only git and bash.
author: 'Sébastien Boulle'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  no_jira:
    description: 'If not empty, no validation is done on JIRA refs.'
    required: false
  allow_temp:
    description: 'If not empty, no validation is done on `fixup!` and `squash!` commits.'
    required: false
runs:
  using: 'node12'
  main: 'index.js'

