#!/bin/bash -e

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

while read -r local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]; then
		:
	else
		if [ "$remote_sha" = $z40 ]; then
			range="$local_sha"
		else
			range="$remote_sha..$local_sha"
		fi
		"$DIR/hooks/commit-message-validator" range "$range" || exit $?
	fi
done

exit 0
