name: 'Commit message validation'

on: pull_request

jobs:
  commit-message-validation:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Commit message validation
        uses: lumapps/commit-message-validator@feat/github_action/push_event
        with:
          no_jira: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
